#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "Version argument is missing"
    exit 1
fi

version=$1

mv "$(find qbittorrenttray_* -type d -print -quit)" qbittorrenttray_$version

pyinstaller qbittorrenttray.spec
mv dist/qbittorrenttray qbittorrenttray_$version/usr/local/bin/qbittorrenttray
dpkg-deb --build qbittorrenttray_$version